sws2apps/sws2apps-api

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/major-change-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- SECURITY.md
> docs: add community and contributing docs

- index.js
- middleware/request-checker.js
- package-lock.json
- package.json
- routes/apps.js
- routes/sws-pocket.js
- utils/updateTracker.js
> feat(app): user request management added

- CHANGELOG.md
- index.js
- middleware/request-checker.js
- package-lock.json
- package.json
- routes/apps.js
- routes/sws-pocket.js
- utils/updateTracker.js
> fix(login): reset login lockout when success

- .github/workflows/code-analysis-heroku.yml
- routes/sws-pocket.js
> fix(login): lockout request on forbidden request

- CHANGELOG.md
- package.json
- routes/sws-pocket.js
> fix(app): login lockout bug

- CHANGELOG.md
- package.json
- routes/sws-pocket.js
> fix: bug fix

- CHANGELOG.md
- package.json
- routes/sws-pocket.js
> main synchronize [skip ci]

- package-lock.json
- package.json
> fix(node-fetch): bump version to 2.6.7

- .github/workflows/deploy-heroku.yml
- package-lock.json
- package.json
> ci(staging-deploy): persist credentials set to false in code checkout

- .github/workflows/deploy-heroku.yml
- CONTRIBUTING.md
- package-lock.json
- package.json
> fix(semantic-release): bump version 19.0.2

- routes/congregation.js
> fix(congregation): enhance congregation id generator

- routes/app.mjs
A new endpoint has been created to feed shields.io
> feat(app): new url for shields.io endpoint

- .github/workflows/code-quality.yml
> ci(ci): separate ci for release and prerelease branch

- .github/workflows/code-quality.yml
- CHANGELOG.md
- package.json
- routes/app.mjs
> build: staging to production

- .github/workflows/dev-to-prod.yml
- .github/workflows/dev-to-staging.yml
- .github/workflows/prod-to-dev.yml
- .github/workflows/prod-to-staging.yml
- .github/workflows/staging-to-dev.yml
- .github/workflows/staging-to-prod.yml
> ci(pipeline): add few pipelines to handle branches rebase

- .github/workflows/dev-to-prod.yml
- .github/workflows/dev-to-staging.yml
- .github/workflows/prod-to-dev.yml
- .github/workflows/prod-to-staging.yml
- .github/workflows/staging-to-dev.yml
- .github/workflows/staging-to-prod.yml
> ci(pipeline): fix git push typo syntax

- routes/congregation.mjs
> fix(congregation): fix bug where vip users are not accessible after password change

- .github/workflows/redeploy-dev.yml
- .github/workflows/redeploy-production.yml
- .github/workflows/redeploy-staging.yml
> ci(pipeline): add direct pipeline for redeployment

- middleware/congregation-auth-checker.js
- routes/congregation.mjs
> feat(middleware): add new congregation auth check middleware

- middleware/auth-checker.mjs
- routes/app.mjs
> feat(auth-checker): improve response when user is not found in the database

- middleware/congregation-auth-checker.js
- routes/congregation.mjs
> feat(congregation): add new route for generating sws pocket user pin

- middleware/update-tracker.mjs
- package-lock.json
> feat(app): add request abort handler

- .github/workflows/deploy-production.yml
> ci(production): remove features to merge changes on prerelease branches

- routes/congregation.mjs
Adding new endpoint to listen request from LMM-OA app to create a new SWS Pocket user.
> feat(congregation): add new endpoint to create sws pocket user

- CHANGELOG.md
- package-lock.json
- package.json
> feat(deps): bump express from 4.17.2 to 4.17.3

- middleware/update-tracker.mjs
> feat(app): add request aborted to the console

- routes/congregation.mjs
> feat(congregation): handle adding existing pocket user, and scope permission by app

- .env.example
- CONTRIBUTING.md
- storage.rules.example
The corrections focus on enhancing the `CONTRIBUTING.md` instructions related to Firebase Emulators setup, obtaining the `GOOGLE_CONFIG_BASE64`, and configuring environment variables.
> docs: Update CONTRIBUTING.md

- src/v3/definition/congregation.ts
> feat(definition): add code for backup upcoming events
